name: Link Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  linkchecker:
    runs-on: ubuntu-latest

    needs: pages-build-deployment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install linkchecker
      run: pip install linkchecker

    - name: Run linkchecker
      run: linkchecker https://uoa-eresearch.github.io/cer-documentation/
