name: Mkdocs Linkcheck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install mkdocs-linkcheck

    - name: Run mkdocs linkcheck
      run: mkdocs linkcheck
